variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/dafny-language-server-linux-mono-build
  NUnitVersion: 3.11.1
  NUnitRunner: NUnit.ConsoleRunner.$NUnitVersion/tools/nunit3-console.exe
  NUnitNugetPackage: nunit.consolerunner -Version $NUnitVersion
  TestBinaries: Binaries/
  SonarScanner_Folder_Version: 4.1.0.1829

stages:
  - prebuild
  - build
  - test

build_image:
  stage: prebuild
  image: docker:latest
  only:
    refs:
      - master
    changes:
      - Dockerfile
      - .gitlab-ci.yml
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $BUILD_IMAGE:latest - < Dockerfile
    - docker push $BUILD_IMAGE:latest

build_server_and_sonar:
  stage: build
  image: $BUILD_IMAGE:latest
  script:
    - cd ..
    - if [ ! -e boogie ];
        then ln -s /opt/boogie;
      fi;
    - cd dafny-language-server/Source
    - mono /opt/SonarScanner.MSBuild.exe begin /k:"dafny-language-server" /o:"hsr" /d:sonar.login="$SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io"
    - nuget restore Dafny.sln
    - msbuild Dafny.sln
    - chmod +x /opt/sonar-scanner-$SonarScanner_Folder_Version/bin/sonar-scanner
    - mono /opt/SonarScanner.MSBuild.exe end /d:sonar.login="$SONAR_TOKEN"
  artifacts:
    paths:
      - Binaries/

test_nunit:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - pushd $TestBinaries; ln -s /opt/z3; popd
    - cd $TestBinaries
    - nuget install $NUnitNugetPackage
    - mono ./$NUnitRunner `find -type f -name \*Test.dll` --inprocess;
  artifacts:
    reports:
      junit: $TestBinaries/TestResult.xml
    paths:
      - Logs/

test_dafny:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - pushd Binaries; ln -s /opt/z3; popd
    - npm install bignumber.js
    - cd Test
    - "find . -path ./LanguageServerTest -prune -o -name '*.dfy' -exec sed -i 's!/optimize !!g' {} +"
    - lit --time-tests -v .
