language: csharp
mono:
  - 5.20.1
dist: xenial
solution: "dafny/Source/Dafny.sln"
addons:
  apt:
    packages:
      - golang-go
      - nodejs
      - npm
install:
  - cd ..
  - sudo npm install bignumber.js
  - sudo pip install lit OutputCheck pyyaml
  - find . -type f
  # Get Boogie
  - git clone https://github.com/boogie-org/boogie.git
  - msbuild boogie/Source/Boogie.sln
  # Get Z3
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
  - unzip z3*.zip && rm *.zip
  - cp -r z3* dafny/Binaries/z3
  # NuGet is a little flakey in legacy TravisCI, use travis_retry command to retry the command if it fails
  - travis_retry nuget restore ${TRAVIS_SOLUTION}
script:
  - msbuild ${TRAVIS_SOLUTION}
  - cd dafny/Test
  # The /optimize flag does not work on mono
  - find . -name "*.dfy" -exec sed -i 's!/optimize !!g' {} +
  - lit --time-tests -v .
