using Microsoft.Boogie;
using Microsoft.Boogie.ModelViewer;
using Microsoft.Boogie.ModelViewer.Dafny;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace DafnyLanguageServer.DafnyAccess
{
    /// <summary>
    /// The .bvd file is the so-called model file.
    /// It is generated by using the compiler argument "/mv:[pathToBVD]" in Dafny.
    /// The model file contains information about counter examples.
    /// This class reads the .bvd file and translates it to a list of specificModels.
    /// </summary>
    public class ModelFileTranslator
    {
        
        public string ModelBvd;

        public ModelFileTranslator() : this(DefaultModelFile.FilePath)
        {
        }

        public ModelFileTranslator(string modelFile)
        {
            ModelBvd = modelFile;
        }

        public List<ILanguageSpecificModel> Translate()
        {
            if (!File.Exists(ModelBvd))
            {
                return new List<ILanguageSpecificModel>();
            }

            string RawBVDContent = ReadModelFile();
            List<Model> models = ParseModels(RawBVDContent);
            List<ILanguageSpecificModel> specificModels = BuildModels(models);

            return specificModels;
        }

        private string ReadModelFile()
        {
            using (var fs = new FileStream(ModelBvd, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            using (var sr = new StreamReader(fs, Encoding.Default))
            {
                return sr.ReadToEnd();
            }
        }

        private List<Model> ParseModels(string modelString)
        {
            return Model.ParseModels(new StringReader(modelString));
        }

        private List<ILanguageSpecificModel> BuildModels(List<Model> modellist)
        {
            var specificModels = new List<ILanguageSpecificModel>();
            foreach (var model in modellist)
            {
                var specifiedModel = Provider.Instance.GetLanguageSpecificModel(model, new ViewOptions() { DebugMode = true, ViewLevel = 3 });
                specificModels.Add(specifiedModel);
            }
            return specificModels;
        }
    }
}
