//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DafnyLanguageServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DafnyLanguageServer.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When symbol is a declaration, it cannot be a usage of itself..
        /// </summary>
        internal static string cannot_use_itself {
            get {
                return ResourceManager.GetString("cannot_use_itself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add usage at unknown symbol..
        /// </summary>
        internal static string cannot_use_unknown_symbol {
            get {
                return ResourceManager.GetString("cannot_use_unknown_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing json config..
        /// </summary>
        internal static string config_could_not_be_parsed {
            get {
                return ResourceManager.GetString("config_could_not_be_parsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file not found at:.
        /// </summary>
        internal static string config_file_not_found {
            get {
                return ResourceManager.GetString("config_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while collecting (counter example) models..
        /// </summary>
        internal static string could_not_collect_models {
            get {
                return ResourceManager.GetString("could_not_collect_models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing compilation..
        /// </summary>
        internal static string could_not_execute_compilation {
            get {
                return ResourceManager.GetString("could_not_execute_compilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Class Scope was not registered..
        /// </summary>
        internal static string global_class_not_registered {
            get {
                return ResourceManager.GetString("global_class_not_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Module given to deep visitor as entry point..
        /// </summary>
        internal static string invalid_module_handed_to_deep_visitor {
            get {
                return ResourceManager.GetString("invalid_module_handed_to_deep_visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When symbol is not a declaration, its declarationOrigin must be given..
        /// </summary>
        internal static string missing_delcaration_origin {
            get {
                return ResourceManager.GetString("missing_delcaration_origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line index must not be negative..
        /// </summary>
        internal static string negativ_line {
            get {
                return ResourceManager.GetString("negativ_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough lines in the given source..
        /// </summary>
        internal static string not_enough_lines {
            get {
                return ResourceManager.GetString("not_enough_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing launch arguments. Please refer to the readme.md.
        /// </summary>
        internal static string not_supported_launch_args {
            get {
                return ResourceManager.GetString("not_supported_launch_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamRedirection and Log must not be the same files..
        /// </summary>
        internal static string stream_and_log_are_same {
            get {
                return ResourceManager.GetString("stream_and_log_are_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected string or TextDocumentChangeEvent-Container at text-document-change event request..
        /// </summary>
        internal static string unexpected_file_type {
            get {
                return ResourceManager.GetString("unexpected_file_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This visitor must only visit declarations..
        /// </summary>
        internal static string visit_only_declarations {
            get {
                return ResourceManager.GetString("visit_only_declarations", resourceCulture);
            }
        }
    }
}
