//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DafnyLanguageServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoggingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DafnyLanguageServer.Resources.LoggingMessages", typeof(LoggingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not redirect output stream. .
        /// </summary>
        public static string could_not_redirect_outputstream {
            get {
                return ResourceManager.GetString("could_not_redirect_outputstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while setting up config. Some Defaults may be in use..
        /// </summary>
        public static string could_not_setup_config {
            get {
                return ResourceManager.GetString("could_not_setup_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Error: .
        /// </summary>
        public static string diagnostic_logical_error {
            get {
                return ResourceManager.GetString("diagnostic_logical_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error: .
        /// </summary>
        public static string diagnostic_syntax_error {
            get {
                return ResourceManager.GetString("diagnostic_syntax_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message:.
        /// </summary>
        public static string error_msg {
            get {
                return ResourceManager.GetString("error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is already the definition..
        /// </summary>
        public static string goto_alreadyIsDef {
            get {
                return ResourceManager.GetString("goto_alreadyIsDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Dafny file is not valid. This affects functionality..
        /// </summary>
        public static string goto_fileNotValid {
            get {
                return ResourceManager.GetString("goto_fileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Defintion found..
        /// </summary>
        public static string goto_notfound {
            get {
                return ResourceManager.GetString("goto_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Defintion found for {0} at L{1}:C{2}.
        /// </summary>
        public static string goto_notfound_at {
            get {
                return ResourceManager.GetString("goto_notfound_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This symbol is a declaration..
        /// </summary>
        public static string hover_isDeclaration {
            get {
                return ResourceManager.GetString("hover_isDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Error: .
        /// </summary>
        public static string inner_error {
            get {
                return ResourceManager.GetString("inner_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no renameable symbol at.
        /// </summary>
        public static string rename_no_symbol {
            get {
                return ResourceManager.GetString("rename_no_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not valid. Use only letters, digits and underscores..
        /// </summary>
        public static string rename_only_digits {
            get {
                return ResourceManager.GetString("rename_only_digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is a reserved word..
        /// </summary>
        public static string rename_reserved_word {
            get {
                return ResourceManager.GetString("rename_reserved_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier must not start with a number..
        /// </summary>
        public static string rename_start_with_number {
            get {
                return ResourceManager.GetString("rename_start_with_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDentifier names must not start with an underscore..
        /// </summary>
        public static string rename_start_with_underscore {
            get {
                return ResourceManager.GetString("rename_start_with_underscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Internal server error while handling {0}.
        /// </summary>
        public static string request_error {
            get {
                return ResourceManager.GetString("request_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling {0}....
        /// </summary>
        public static string request_handle {
            get {
                return ResourceManager.GetString("request_handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully handled.
        /// </summary>
        public static string request_success {
            get {
                return ResourceManager.GetString("request_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating File: .
        /// </summary>
        public static string request_update {
            get {
                return ResourceManager.GetString("request_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating Diagnostics....
        /// </summary>
        public static string request_update_diagnostics {
            get {
                return ResourceManager.GetString("request_update_diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server closed..
        /// </summary>
        public static string server_closed {
            get {
                return ResourceManager.GetString("server_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is running..
        /// </summary>
        public static string server_running {
            get {
                return ResourceManager.GetString("server_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is starting....
        /// </summary>
        public static string server_starting {
            get {
                return ResourceManager.GetString("server_starting", resourceCulture);
            }
        }
    }
}
