//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DafnyLanguageServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Requests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Requests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DafnyLanguageServer.Resources.Requests", typeof(Requests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Lens.
        /// </summary>
        public static string codelens {
            get {
                return ResourceManager.GetString("codelens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation.
        /// </summary>
        public static string compile {
            get {
                return ResourceManager.GetString("compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Completion.
        /// </summary>
        public static string completion {
            get {
                return ResourceManager.GetString("completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Example.
        /// </summary>
        public static string counterExample {
            get {
                return ResourceManager.GetString("counterExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Definition.
        /// </summary>
        public static string definitions {
            get {
                return ResourceManager.GetString("definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover Information.
        /// </summary>
        public static string hover {
            get {
                return ResourceManager.GetString("hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dafny.showReferences.
        /// </summary>
        public static string showRefReq {
            get {
                return ResourceManager.GetString("showRefReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched File Change.
        /// </summary>
        public static string watchedFileChanged {
            get {
                return ResourceManager.GetString("watchedFileChanged", resourceCulture);
            }
        }
    }
}
